{{- if and .Values.app.config.security.ssl.enabled .Values.app.config.security.ssl.secret.generate }}
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: {{ .Values.app.config.security.ssl.secret.name }}
  labels:
    app: restconf-driver
    release: {{ .Release.Name }}
data:
{{ ( include "gen-cert" . ) | indent 2 }}
{{- end }}